config/routes.rb
Rails.application.routes.draw do 
  root 'activity_events#index'
  resources :activities
  resources :users
  resources :activity_events
end

app/models/user.rb
class User < ApplicationRecord
    has_many :activity_events
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_path, notice: "User was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.expect(user: [ :name, :email ])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit "Create", class: "cancel-button"  %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<%= turbo_frame_tag "modal" do %>
	<div class="modal">
		<h1>Editing user</h1>

		<%= render "form", user: @user %>

		<br>

		<table class="table_i">
			<tr class="tr_i">
				<td class="td_i">
		  	<%= link_to "View", @user, class: "cancel-button" %>
				</td>
			</tr>
			<tr class="tr_i">
				<td class="td_i">
		  	<%= link_to "Users", users_path, class: "cancel-button", data: { turbo_frame: "_top" }  %>
			<%= link_to "Events", activity_events_path, class: "cancel-button", data: { turbo_frame: "_top" }  %>
				</td>
			</tr>
		</table>
	</div>
<% end %>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Users" %>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>
<div class="link-text">
  <%= link_to "Back to Events", activity_events_path %>
</div>

app/views/users/new.html.erb
<%= turbo_frame_tag "modal" do %>
	<div class="modal">
		<h1>New user</h1>

		<%= render "form", user: @user %>

		<br>

		<div class="link-text">
		  	<%= link_to "Users", users_path, class: "cancel-button", data: { turbo_frame: "_top" }  %>
			<%= link_to "Events", activity_events_path, class: "cancel-button", data: { turbo_frame: "_top" } %>  
		</div>
	</div>
<% end %>

app/views/users/show.html.erb
<%= turbo_frame_tag "modal" do %>
	<div class="modal">
		<%= render @user %>
		
		<table class="table_i">
			<tr class="tr_i">
				<td class="td_i">
		  <%= link_to "Edit", edit_user_path(@user), class: "cancel-button" %>
		  <%= button_to "Delete", @user, method: :delete, class: "cancel-button", data: { turbo_frame: "_top" } %>
				</td>
			</tr>
			<tr class="tr_i">
				<td class="td_i">
		  <%= link_to "Users", users_path, class: "cancel-button", data: { turbo_frame: "_top" }  %>
		  <%= link_to "Events", activity_events_path, class: "cancel-button", data: { turbo_frame: "_top" }  %>
				</td>
			</tr>
		</table>
	</div>
<% end %>