config/routes.rb
Rails.application.routes.draw do 
  root 'activity_events#index'
  resources :activities
  resources :users
  resources :activity_events
end

app/models/activity.rb
class Activity < ApplicationRecord
    has_many :activity_events
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: %i[ show edit update destroy ]

  # GET /activities or /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1 or /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
    @activity_for_dropdown = Activity.all.map { |activity| [activity.ActivityName, activity.id] } # Or any other desired attributes
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities or /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: "Activity was successfully created." }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1 or /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: "Activity was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1 or /activities/1.json
  def destroy
    @activity.destroy!

    respond_to do |format|
      format.html { redirect_to activities_path, notice: "Activity was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def activity_params
      params.expect(activity: [ :ActivityName, :Description, :ActivityType ])
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_activity.html.erb
<div id="<%= dom_id activity %>">
  <p>
    <strong>Activityname:</strong>
    <%= activity.ActivityName %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= activity.Description %>
  </p>

  <p>
    <strong>Activitytype:</strong>
    <%= activity.ActivityType %>
  </p>

</div>

app/views/activities/_form.html.erb
<%= form_with(model: activity) do |form| %>
  <% if activity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% activity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :ActivityName, style: "display: block" %>
    <%= form.text_field :ActivityName %>
  </div>

  <div>
    <%= form.label :Description, style: "display: block" %>
    <%= form.text_field :Description %>
  </div>

  <div>
    <%= form.label :ActivityType, style: "display: block" %>
    <%= form.select :ActivityType, @activity_for_dropdown %>
  </div>


  <div>
    <%= form.submit "Create", class: "cancel-button"  %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<%= turbo_frame_tag "modal" do %>
	<div class="modal">
		<h1>Editing activity</h1>

		<%= render "form", activity: @activity %>

		<br>

		<table class="table_i">
			<tr class="tr_i">
				<td class="td_i">
		  	<%= link_to "View", @activity, class: "cancel-button" %>
				</td>
			</tr>
			<tr class="tr_i">
				<td class="td_i">
		  <%= link_to "Activities", activities_path, class: "cancel-button", data: { turbo_frame: "_top" }  %>
		  <%= link_to "Events", activity_events_path, class: "cancel-button", data: { turbo_frame: "_top" }  %>
				</td>
			</tr>
		</table>
	</div>
<% end %>

app/views/activities/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Activities" %>

<h1>Activities</h1>

<div id="activities">
  <% @activities.each do |activity| %>
    <%= render activity %>
    <p>
      <%= link_to "Show this activity", activity %>
    </p>
  <% end %>
</div>

<%= link_to "New activity", new_activity_path %>
<div class="link-text">
  <%= link_to "Back to Events", activity_events_path %>
</div>

app/views/activities/new.html.erb
<%= turbo_frame_tag "modal" do %>
	<div class="modal">
		<h1>New activity</h1>

		<%= render "form", activity: @activity %>

		<br>
		
		<div>
			<%= link_to "Activities", activities_path, class: "cancel-button", data: { turbo_frame: "_top" }  %>
			<%= link_to "Events", activity_events_path, class: "cancel-button", data: { turbo_frame: "_top" }  %>
		</div>
	</div>
<% end %>

app/views/activities/show.html.erb
<%= turbo_frame_tag "modal" do %>
	<div class="modal">
		<%= render @activity %>

		<table class="table_i">
			<tr class="tr_i">
				<td class="td_i">
		  			<%= link_to "Edit", edit_activity_path(@activity), class: "cancel-button" %>
		  			<%= button_to "Delete", @activity, method: :delete, class: "cancel-button", data: { turbo_frame: "_top" } %>
				</td>
			</tr>
			<tr class="tr_i">
				<td class="td_i">
		  			<%= link_to "Activities", activities_path, class: "cancel-button", data: { turbo_frame: "_top" } %>
					<%= link_to "Events", activity_events_path, class: "cancel-button", data: { turbo_frame: "_top" } %>
				</td>
			</tr>
		</table>
	</div>
<% end %>