config/routes.rb
Rails.application.routes.draw do 
  root 'activity_events#index'
  resources :activities
  resources :users
  resources :activity_events
end

app/models/activity_event.rb
class ActivityEvent < ApplicationRecord
    belongs_to :user
    belongs_to :activity
end

app/controllers/activity_events_controller.rb
class ActivityEventsController < ApplicationController
  before_action :set_activity_event, only: %i[ show edit update destroy ]

  # GET /activity_events or /activity_events.json
  def index
    # Get the current date
    today = Date.current

    # Calculate the date of the Monday of the current week
    # Date.current.beginning_of_week defaults to Monday as the start of the week.
    this_monday = today.beginning_of_week

    @activity_events_Mon_TD = ActivityEvent.select{ |event| event.is_completed == false && event.due_date == this_monday }
    @activity_events_Tue_TD = ActivityEvent.select{ |event| event.is_completed == false && event.due_date == this_monday + 1.day }
    @activity_events_Wed_TD = ActivityEvent.select{ |event| event.is_completed == false && event.due_date == this_monday + 2.day }
    @activity_events_Thr_TD = ActivityEvent.select{ |event| event.is_completed == false && event.due_date == this_monday + 3.day }
    @activity_events_Fri_TD = ActivityEvent.select{ |event| event.is_completed == false && event.due_date == this_monday + 4.day }
    @activity_events_Sat_TD = ActivityEvent.select{ |event| event.is_completed == false && event.due_date == this_monday + 5.day }
    @activity_events_Sun_TD = ActivityEvent.select{ |event| event.is_completed == false && event.due_date == this_monday + 6.day }

    @activity_events_Mon_Dn = ActivityEvent.select{ |event| event.is_completed == true && event.due_date == this_monday }
    @activity_events_Tue_Dn = ActivityEvent.select{ |event| event.is_completed == true && event.due_date == this_monday + 1.day }
    @activity_events_Wed_Dn = ActivityEvent.select{ |event| event.is_completed == true && event.due_date == this_monday + 2.day }
    @activity_events_Thr_Dn = ActivityEvent.select{ |event| event.is_completed == true && event.due_date == this_monday + 3.day }
    @activity_events_Fri_Dn = ActivityEvent.select{ |event| event.is_completed == true && event.due_date == this_monday + 4.day }
    @activity_events_Sat_Dn = ActivityEvent.select{ |event| event.is_completed == true && event.due_date == this_monday + 5.day }
    @activity_events_Sun_Dn = ActivityEvent.select{ |event| event.is_completed == true && event.due_date == this_monday + 6.day }
  end

  # GET /activity_events/1 or /activity_events/1.json
  def show
    @activity = Activity.find{ |activity| activity.id == @activity_event.activity_id }
    @activity_name = @activity.ActivityName
    @user= User.find{ |user| user.id == @activity_event.user_id }
    @user_name = @user.name
    # @acitivy_description = @activity.Description
  end

  # GET /activity_events/new
  def new
    @activity_event = ActivityEvent.new
    @users_for_dropdown = User.all.map { |user| [user.name, user.id] } # Or any other desired attributes
    @activities_for_dropdown = Activity.all.map { |activity| [activity.ActivityName, activity.id] } # Or any other desired attributes
  end

  # GET /activity_events/1/edit
  def edit
    @users_for_dropdown = User.all.map { |user| [user.name, user.id] } # Or any other desired attributes
    @activities_for_dropdown = Activity.all.map { |activity| [activity.ActivityName, activity.id] } # Or any other desired attributes
  end

  # POST /activity_events or /activity_events.json
  def create
    @activity_event = ActivityEvent.new(activity_event_params)

    respond_to do |format|
      if @activity_event.save
        format.html { redirect_to @activity_event, notice: "Activity event was successfully created." }
        format.json { render :show, status: :created, location: @activity_event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activity_events/1 or /activity_events/1.json
  def update
    respond_to do |format|
      if @activity_event.update(activity_event_params)
        format.html { redirect_to @activity_event, notice: "Activity event was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @activity_event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @activity_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activity_events/1 or /activity_events/1.json
  def destroy
    @activity_event.destroy!

    respond_to do |format|
      format.html { redirect_to activity_events_path, notice: "Activity event was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity_event
      @activity_event = ActivityEvent.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def activity_event_params
      params.expect(activity_event: [ :due_date, :is_completed, :created_at, :updated_at, :user_id, :activity_id, :description ])
    end
end

app/helpers/activity_events_helper.rb
module ActivityEventsHelper
end

app/views/activity_events/_activity_event.html.erb
<div id="<%= dom_id activity_event %>">
  <p>
    <strong>Due date:</strong>
    <%= activity_event.due_date %>
  </p>

  <p>
    <strong>Is completed:</strong>
    <%= activity_event.is_completed %>
  </p>

  <p>
    <strong>Created at:</strong>
    <%= activity_event.created_at %>
  </p>

  <p>
    <strong>Updated at:</strong>
    <%= activity_event.updated_at %>
  </p>

  <p>
    <strong>User:</strong>
    <%= @user_name %>
  </p>

  <p>
    <strong>Activity:</strong>
    <%= @activity_name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= activity_event.description %>
  </p>

</div>

app/views/activity_events/_form.html.erb
<%= form_with(model: activity_event) do |form| %>
  <% if activity_event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(activity_event.errors.count, "error") %> prohibited this activity_event from being saved:</h2>

      <ul>
        <% activity_event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :due_date, style: "display: block" %>
    <%= form.date_field :due_date %>
  </div>

  <div>
    <%= form.label :is_completed, style: "display: block" %>
    <%= form.checkbox :is_completed %>
  </div>



  <div>
    <%= form.label :user_id, style: "display: block" %>
	<%= form.select :user_id, @users_for_dropdown%>
  </div>

  <div>
    <%= form.label :activity_id, style: "display: block" %>
	<%= form.select :activity_id, @activities_for_dropdown%>
  </div>
  
  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>


  <div>
    <%= form.submit "Create", class: "cancel-button" %>
  </div>
<% end %>

app/views/activity_events/edit.html.erb
<%= turbo_frame_tag "modal" do %>
	<div class="modal">
		<h1>Editing activity event</h1>
	
		<%= render "form", activity_event: @activity_event %>
	
		<br>
	
		<table class="table_i">
			<tr class="tr_i">
				<td class="td_i">
		  <%= link_to "View", @activity_event, class: "cancel-button" %>  
				</td>
			</tr>
			<tr class="tr_i">
				<td class="td_i">
			<%= link_to "Events", activity_events_path, class: "cancel-button", data: { turbo_frame: "_top" }  %>
				</td>
			</tr>
		</table>
	</div>
<% end %>

app/views/activity_events/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Activity events" %>

<% week_start = Date.current.beginning_of_week(:monday) %>
<% mon_date = week_start
   tue_date = week_start + 1.day
   wed_date = week_start + 2.days
   thu_date = week_start + 3.days
   fri_date = week_start + 4.days
   sat_date = week_start + 5.days
   sun_date = week_start + 6.days %>

<div class="text-title">
  <h1>Activity events</h1>
</div>

<table class="grid">
  <thead>
    <tr>
      <th></th>
      <th class="<%= 'today-cell' if mon_date == Date.current %>">Monday</th>
      <th class="<%= 'today-cell' if tue_date == Date.current %>">Tuesday</th>
      <th class="<%= 'today-cell' if wed_date == Date.current %>">Wednesday</th>
      <th class="<%= 'today-cell' if thu_date == Date.current %>">Thursday</th>
      <th class="<%= 'today-cell' if fri_date == Date.current %>">Friday</th>
      <th class="<%= 'today-cell' if sat_date == Date.current %>">Saturday</th>
      <th class="<%= 'today-cell' if sun_date == Date.current %>">Sunday</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td class="category">To Do</td>
	  <!-- Monday -->
      <td class="<%= 'today-cell' if mon_date == Date.current %>">
  		<% @activity_events_Mon_TD.each do |activityEvent| %>
    		<%= link_to  activityEvent.activity.ActivityName, activityEvent, data: { turbo_frame: "modal" } %> <br/>
  		<% end %>
	  </td>
	  <!-- Tuesday -->
      <td class="<%= 'today-cell' if tue_date == Date.current %>">
  		<% @activity_events_Tue_TD.each do |activityEvent| %>
    		<%= link_to  activityEvent.activity.ActivityName, activityEvent, data: { turbo_frame: "modal" } %> <br/>
  		<% end %>
	  </td>
	  <!-- Wednesday -->
      <td class="<%= 'today-cell' if wed_date == Date.current %>">
  		<% @activity_events_Wed_TD.each do |activityEvent| %>
    		<%= link_to  activityEvent.activity.ActivityName, activityEvent, data: { turbo_frame: "modal" } %> <br/>
  		<% end %>
	  </td>
	  <!-- Thursday -->
      <td class="<%= 'today-cell' if thu_date == Date.current %>">
  		<% @activity_events_Thr_TD.each do |activityEvent| %>
    		<%= link_to  activityEvent.activity.ActivityName, activityEvent, data: { turbo_frame: "modal" } %> <br/>
  		<% end %>
	  </td>
	  <!-- Friday -->
      <td class="<%= 'today-cell' if fri_date == Date.current %>">
  		<% @activity_events_Fri_TD.each do |activityEvent| %>
    		<%= link_to  activityEvent.activity.ActivityName, activityEvent, data: { turbo_frame: "modal" } %> <br/>
  		<% end %>
	  </td>
	  <!-- Saturday -->
      <td class="<%= 'today-cell' if sat_date == Date.current %>">
  		<% @activity_events_Sat_TD.each do |activityEvent| %>
    		<%= link_to  activityEvent.activity.ActivityName, activityEvent, data: { turbo_frame: "modal" } %> <br/>
  		<% end %>
	  </td>
	  <!-- Sunday -->
      <td class="<%= 'today-cell' if sun_date == Date.current %>">
  		<% @activity_events_Sun_TD.each do |activityEvent| %>
    		<%= link_to  activityEvent.activity.ActivityName, activityEvent, data: { turbo_frame: "modal" } %> <br/>
  		<% end %>
	  </td>
    </tr>
    <!-- In Progress -->
    <tr>
      <td class="category">Done</td>
	  <!-- Monday -->
      <td class="<%= 'today-cell' if mon_date == Date.current %>">
  		<% @activity_events_Mon_Dn.each do |activityEvent| %>
    		<%= link_to  activityEvent.activity.ActivityName, activityEvent, data: { turbo_frame: "modal" } %> <br/>
  		<% end %>
	  </td>
	  <!-- Tuesday -->
      <td class="<%= 'today-cell' if tue_date == Date.current %>">
  		<% @activity_events_Tue_Dn.each do |activityEvent| %>
    		<%= link_to  activityEvent.activity.ActivityName, activityEvent, data: { turbo_frame: "modal" } %> <br/>
  		<% end %>
	  </td>
	  <!-- Wednesday -->
      <td class="<%= 'today-cell' if wed_date == Date.current %>">
  		<% @activity_events_Wed_Dn.each do |activityEvent| %>
    		<%= link_to  activityEvent.activity.ActivityName, activityEvent, data: { turbo_frame: "modal" } %> <br/>
  		<% end %>
	  </td>
	  <!-- Thursday -->
      <td class="<%= 'today-cell' if thu_date == Date.current %>">
  		<% @activity_events_Thr_Dn.each do |activityEvent| %>
    		<%= link_to  activityEvent.activity.ActivityName, activityEvent, data: { turbo_frame: "modal" } %> <br/>
  		<% end %>
	  </td>
	  <!-- Friday -->
      <td class="<%= 'today-cell' if fri_date == Date.current %>">
  		<% @activity_events_Fri_Dn.each do |activityEvent| %>
    		<%= link_to  activityEvent.activity.ActivityName, activityEvent, data: { turbo_frame: "modal" } %> <br/>
  		<% end %>
	  </td>
	  <!-- Saturday -->
      <td class="<%= 'today-cell' if sat_date == Date.current %>">
  		<% @activity_events_Sat_Dn.each do |activityEvent| %>
    		<%= link_to  activityEvent.activity.ActivityName, activityEvent, data: { turbo_frame: "modal" } %> <br/>
  		<% end %>
	  </td>
	  <!-- Sunday -->
      <td class="<%= 'today-cell' if sun_date == Date.current %>">
  		<% @activity_events_Sun_Dn.each do |activityEvent| %>
    		<%= link_to  activityEvent.activity.ActivityName, activityEvent, data: { turbo_frame: "modal" } %> <br/>
  		<% end %>
	  </td>
    </tr>

  </body>

  <tfoot>
  </tfoot>
</table>

app/views/activity_events/new.html.erb
<%= turbo_frame_tag "modal" do %>
	<div class="modal">
		<h1>New activity event</h1>

		<%= render "form", activity_event: @activity_event %>

		<br>

		<div>
			<%= link_to "Events", activity_events_path, class: "cancel-button", data: { turbo_frame: "_top" } %>  
		</div>
	</div>
<% end %>

app/views/activity_events/show.html.erb
<%= turbo_frame_tag "modal" do %>
	<div class="modal">

		<%= render @activity_event %>

		<table class="table_i">
			<tr class="tr_i">
				<td class="td_i">
			<%= link_to "Edit", edit_activity_event_path(@activity_event), class: "cancel-button" %>
			<%= button_to "Delete", @activity_event, method: :delete, class: "cancel-button", data: { turbo_frame: "_top" } %>
				</td>
			</tr>
			<tr class="tr_i">
				<td class="td_i">
			<%= link_to "Events", activity_events_path, class: "cancel-button", data: { turbo_frame: "_top" } %>  
				</td>
			</tr>
		</table>
	</div>
<% end %>